# Generated by Django 3.0.8 on 2020-07-09 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200708_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
